#!/usr/bin/env python

import rospy
from sensor_msgs.msg import CompressedImage
from std_msgs.msg import Bool

import cv2
from cv_bridge import CvBridge, CvBridgeError
import json
import numpy as np
import os.path

##################################################################################

# Import vehicle config:
f = open(os.path.dirname(__file__) + "/../../json/config.json")
fData = json.load(f)

# User-define image log path:
savePath = "/home/ubuntu/catkin_ws/logs/jpg/"

##################################################################################

#
def getTimestamp(timestamps, counter):

    # Append timestamps with image:
    now = rospy.get_rostime().nsecs * 10 ** 9
    timestamps = np.vstack((timestamps, np.array([[f"{counter:04d}", now.secs]])))
    print(now.secs)
    
    return timestamps

#
def getFileName(counter):

    # Generate file name:
    name = "IMG" + f"{counter:04d}" + ".jpg"

    return name

#
def getFilePath(name):

    # Check if log path exists:
    if not os.path.exists(savePath):
        os.makedirs(savePath)

    # Generate file path:
    path = savePath + name

    return path

#
def logTimestamps(timestamps):

    #
    np.savetxt(savePath + "timestamps.csv", timestamps, delimiter=",", fmt="%s")

#
def callbackImage(data):

    # https://gist.github.com/rethink-imcmahon/77a1a4d5506258f3dc1f

    #
    if shouldSample.data:

        #
        try:

            # Convert ROS CompressedImage to CV2:
            image = bridge.imgmsg_to_cv2(data.data, "bgr8")

        except CvBridgeError:
            print("Error converting CompressedImage to CV2")

        #
        else:

            # Save CV2 as jpg:
            global path
            cv2.imwrite(path. image)

#
def main():
    
    # Initiate counter and time stamp storage:
    global timestamps
    timestamps = np.empty((0, 2))
    counter = 0

    # 
    rate = rospy.Rate(sample_rate)
    while not rospy.is_shutdown():

        # Generate image timestamp:
        timestamps = getTimestamp(timestamps, counter)

        # Generate file name:
        name = getFileName(counter)

        # Generate file path:
        global path
        path = getFilePath(name)

        # Log image:
        shouldSample.data = True
        rospy.wait_for_message("/" + nameUAV + "/raspicam_node/image/compressed", CompressedImage)
        shouldSample.data = False

        # Incremement counter:
        counter += 1
        rate.sleep()

##################################################################################

#
if __name__=="__main__":

    # Initialize node:
    rospy.init_node("messcv_rpicam_stills")

    # Create objects:
    shouldSample = Bool()
    shouldSample.data = True

    # Retrieve config data:
    nameUAV = fData["uav_name"]
    sample_rate = fData["still_rate"]
    bridge = CvBridge()

    # Initialize publishers and subscribers:
    rospy.Subscriber("/" + nameUAV + "/raspicam_node/image/compressed", CompressedImage, callbackImage)

    #
    try:

        # Sample images:
        main()
        rospy.spin()

        # On shut down, log timestamps of images:
        rospy.on_shutdown(lambda: logTimestamps(timestamps))

    #
    except rospy.ROSInterruptException:
        pass
        
